---

- name: Test issue 234
  hosts: all
  gather_facts: true
  tasks:
    - name: Test issue 234
      block:
        - name: Setup firewalld
          include_role:
            name: linux-system-roles.firewall
          vars:
            firewall:
              # Wipe existing config and replace with the config defined below.
              - previous: replaced

              # For some reason the cockpit and dhcpv6-client are enabled by default.
              # Explicitly disable them.
              - service:
                  - cockpit
                  - dhcpv6-client
                state: disabled

              # Only allow the ports below.
              - zone: public
                state: enabled
                permanent: true
                interface: enp1s0
                services:
                  - ssh
                port:
                    # Web ports
                  - '80/tcp'    # HTTP
                  - '443/tcp'   # HTTPS
                  - '636/tcp'   # LDAPS

                # NOTE: Until https://github.com/linux-system-roles/firewall/pull/234 is resolved manually persist changes:
                #   firewall-cmd --runtime-to-permanent
                masquerade: true
                forward_port:
                  - port: 1194
                    proto: udp
                    toaddr: 192.168.1.1
                    toport: 1195

                  - port: 16001
                    proto: tcp
                    toaddr: 192.168.1.21
                    toport: 16001

        - name: Debug1
          command: firewall-cmd --list-all-zones
          changed_when: false

        - name: Reboot
          reboot:

        - name: Debug2
          command: firewall-cmd --list-all-zones
          changed_when: false
